version: "2"

services:
  sparagn-media-service:
    build:
      context: ../
      dockerfile: $PWD/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      .env.develop
    networks:
    - back-tier

  minio1:
    image:  minio/minio:RELEASE.2020-12-18T03-27-42Z
    volumes:
      - data1-1:/data
      - ./test/.minio/config:/root/.minio
    ports:
      - "9000:9000"
    networks:
      - back-tier
    env_file:
      .env.develop
    entrypoint: sh
    command: -c 'mkdir -p /data/bucket-categ && /usr/bin/minio server /data'

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:

networks:
  back-tier: